[package]
name = "auxtion"
version = "1.0.0"

[dependencies]
"php/php-32" = "8.2.0"

[fs]
# Mount your app files into the container
"/app" = "."

[[command]]
name = "web"
module = "php/php-32"
runner = "php"
args = ["-S", "0.0.0.0:8080", "-t", "/app"]

[permissions]
# Allow outbound TCP to your DB
net = [
  { outbound = ["db.us-losa1.bengt.wasmernet.com:16751"] }
]
